[package]
name = "solovay_strassen"
version = "0.1.0"
authors = ["cjayross <calvinjayross@gmail.com>"]
edition = "2018"
description = "A simple implementation of the Solovay-Strassen primality test."
license = "MIT"
keywords = ["solovay", "strassen", "prime", "primality", "test"]
categories = ["cryptography", "mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "~0.7.0"
rayon = "~1.2.1"
