[package]
name = "solovay_strassen"
version = "0.1.0"
authors = ["cjayross <calvinjayross@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { git = "https://github.com/rust-lang-nursery/rand" }
rayon = "~1.2.1"
clap = "~2.33.0"
